### ISSUE TITLE
Occurs after entered an captcha. Might be incorrect reading of the amount of proxies.

### ISSUE THREAD

**Issue by inieuwoudt1** [EarsKilla/Steam-Account-Generator#10]
[2019-04-26 14:16:40.9062|FATAL|SteamAccCreator.Program.<>c.<Main>b__5_0(Object s, UnhandledExceptionEventArgs e)|7]: FATAL_UNHANDLED_EXCEPTION
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
   at System.Text.RegularExpressions.MatchCollection.get_Item(Int32 i)
   at SteamAccCreator.Web.HttpHandler.GetCaptchaImageraw()
   at SteamAccCreator.Gui.CaptchaDialog.LoadCaptcha(Action`1 updateStatus, CaptchaSolvingConfig config)
   at SteamAccCreator.Gui.CaptchaDialog..ctor(HttpHandler httpHandler, Action`1 updateStatus, CaptchaSolvingConfig config)
   at SteamAccCreator.Gui.AccountCreator.ShowCaptchaDialog(HttpHandler httpHandler, Action`1 updateStatus, CaptchaSolvingConfig captchaConfig)
   at SteamAccCreator.Gui.AccountCreator.StartCreation()
   at SteamAccCreator.Gui.AccountCreator.<Run>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by inieuwoudt1** [comment]
This however, might have been an earlier release.

**Comment by EarsKilla** [comment]
as i understand this exception throw at parsing captcha gid
