### ISSUE TITLE
Status dissapears when resolving captcha

### ISSUE THREAD

**Issue by michaelish** [EarsKilla/Steam-Account-Generator#25]
`[2019-07-04 16:53:00.9985|DEBUG|SteamAccCreator.Web.HttpHandler.SolveCaptcha(Action`1 updateStatus, Configuration config)|4]: Getting captcha...
[2019-07-04 16:53:01.1834|DEBUG|SteamAccCreator.Web.HttpHandler.SolveCaptcha(Action`1 updateStatus, Configuration config)|4]: Recognizing captcha...
[2019-07-04 16:53:01.1834|DEBUG|SteamAccCreator.Web.HttpHandler.SolveCaptcha(Action`1 updateStatus, Configuration config)|4]: Recognizing captcha via TwoCaptcha/RuCaptcha
[2019-07-04 16:53:01.8189|WARN|SteamAccCreator.Program.<>c.<Main>b__5_1(Object s, FirstChanceExceptionEventArgs e)|4]: FIRST_CHANCE_EXCEPTION
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
====== END ======
[2019-07-04 16:53:01.8189|WARN|SteamAccCreator.Program.<>c.<Main>b__5_1(Object s, FirstChanceExceptionEventArgs e)|4]: FIRST_CHANCE_EXCEPTION
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
====== END ======
[2019-07-04 16:53:01.8189|WARN|SteamAccCreator.Program.<>c.<Main>b__5_1(Object s, FirstChanceExceptionEventArgs e)|4]: FIRST_CHANCE_EXCEPTION
System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
====== END ======
[2019-07-04 16:53:01.8189|DEBUG|SteamAccCreator.Web.HttpHandler.SolveCaptcha(Action`1 updateStatus, Configuration config)|4]: TwoCaptcha/RuCaptcha image upload response: 
[2019-07-04 16:53:01.8189|WARN|SteamAccCreator.Gui.AccountCreator.StartCreation()|4]: Captcha solving: Error: 

====== END ======
[2019-07-04 16:57:22.2584|WARN|SteamAccCreator.Program.<>c.<Main>b__5_1(Object s, FirstChanceExceptionEventArgs e)|10]: FIRST_CHANCE_EXCEPTION
System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.HttpWebRequest.GetResponse()`

I can create accounts fine on my own IP, using 2captcha. I can also create accounts fine using my private proxy and manually solving captcha. But when I use both proxy and captcha solver the program resolves captcha, briefly waits for email verification before it goes back to captcha and status will dissapear, leaving a blank.

**Comment by EarsKilla** [comment]
here will be captcha error but it's empty. 
> ```
> [2019-07-04 16:53:01.8189|DEBUG|SteamAccCreator.Web.HttpHandler.SolveCaptcha(Action`1 updateStatus, Configuration config)|4]: TwoCaptcha/RuCaptcha image upload response:
> [2019-07-04 16:53:01.8189|WARN|SteamAccCreator.Gui.AccountCreator.StartCreation()|4]: Captcha solving: Error:
> 
> ====== END ======
> ```

Upload image response empty? lol
---
> `System.Net.WebException: The remote server returned an error: (429) Too Many Requests.`
🤔

---

Still need to improve captcha solving... So yup, it's bug

**Comment by michaelish** [comment]
![Untitled314](https://user-images.githubusercontent.com/2786192/60742237-575d9a00-9f21-11e9-8567-5e17c8445425.png)

After "Creating Account..." the first one will become same as the second one

**Comment by EarsKilla** [comment]
It's empty error. so it's ok (no, just bug)

**Comment by michaelish** [comment]
anyway to get around this bug before steam sales end?

**Comment by despa1r1337** [comment]
> anyway to get around this bug before steam sales end?

 if you have solved your problem, you can close the issue

**Comment by EarsKilla** [comment]
Better to keep opened and i don't forget about this issue

**Comment by crx9** [comment]
I use 1.1.3.3,when I enter the correct captcha and click Ok,it always asks me to retype the captcha。
I use  2.0.1,Error: Getting captcha GID error!

**Comment by EarsKilla** [comment]
> I use 1.1.3.3,when I enter the correct captcha and click Ok,it always asks me to retype the captcha。
https://github.com/steam-account-creator/Steam-Account-Generator/wiki/F.A.Q.#ip-disallowed-or-banned--endless-captcha

---

> I use 2.0.1,Error: Getting captcha GID error!
that's interesting 🤔

**Comment by crx9** [comment]
> > I use 1.1.3.3,when I enter the correct captcha and click Ok,it always asks me to retype the captcha。
> 
> https://github.com/steam-account-creator/Steam-Account-Generator/wiki/F.A.Q.#ip-disallowed-or-banned--endless-captcha
> but it can be related to issue with 2.0.1
> 
> > I use 2.0.1,Error: Getting captcha GID error!
> 
> that's interesting 🤔

the 2.0.1,Getting captcha GID error,why?

**Comment by crx9** [comment]
> > 我使用1.1.3.3，当输入正确的captcha并单击OK时，它总是要求我重新键入captcha。
> 
> [https：/github.com/蒸汽-帐户-创建者/蒸汽-帐户-生成器/wiki/F.A.Q.#ip-不允许或禁止-无休止的-captcha](https://github.com/steam-account-creator/Steam-Account-Generator/wiki/F.A.Q.#ip-disallowed-or-banned--endless-captcha)
> 但这可能与2.0.1有关
> 
> > 我使用2.0.1，错误：获取captcha GID错误！
> 
> 这很有趣🤔

i use  the public mail to create acc on 1.1.3.3,but it always asks me to retype the captcha,so sad

**Comment by despa1r1337** [comment]
> I use 1.1.3.3,when I enter the correct captcha and click Ok,it always asks me to retype the captcha。

Sometimes captcha may not work correctly, try to close the program and run it again. This usually happens to those who use vpn.

**Comment by EarsKilla** [comment]
Please, retry with [dev 2.1.0](https://github.com/steam-account-creator/Steam-Account-Generator/releases/tag/v2.1.0)
